language: cpp

notifications:
  email: false

os:
  - linux
  - osx

before_install:
  # g++4.8.1
  - if [ "$OSTYPE" == "linux-gnu" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi; sudo apt-get update -qq

install:
  # g++4.8.1
  - if [ "$OSTYPE" == "linux-gnu" ]; then sudo apt-get install -qq g++-4.8; fi

compiler:
  - clang
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make
