language: cpp

notifications:
  email: false

os:
  - linux
  - osx

before_install:
  # g++4.8.1
  - if [ "$OSTYPE" == "linux-gnu" && "$CXX" = "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; sudo apt-get update -qq; fi

install:
  # g++4.8.1
  - if [ "$OSTYPE" == "linux-gnu" && "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; export CXX="g++-4.8"; fi

compiler:
  - clang
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make
